version: '3'

vars:
  NAME: "consulic"
  NETWORK: "{{.NAME}}"
  VOLUME: "{{.NAME}}"
  CONTAINER: "{{.NAME}}"
  MAJOR:
    sh: git describe --tags --abbrev=0 | cut -f1 -d.
  MINOR:
    sh: git describe --tags --abbrev=0 | cut -f2 -d.
  PATCH:
    sh: git describe --tags --abbrev=0 | cut -f3 -d.
  BRANCH:
    sh: git symbolic-ref --short HEAD | cut -f1 -d-
  COMMITS:
    sh: git describe --tags | cut -f2 -d-
  VERSION0: "{{.MAJOR}}.{{.MINOR}}.{{.PATCH}}"
  VERSION1:
    sh: if [ "{{.BRANCH}}" != "main" ]; then echo "{{.VERSION0}}-issue.{{.BRANCH}}"; else echo "{{.VERSION0}}"; fi 
  VERSION:
    sh: if [ ! -z "{{.COMMITS}}" ] && [ "{{.COMMITS}}" != "{{.VERSION0}}" ]; then echo "{{.VERSION1}}-build.{{.COMMITS}}"; else echo "{{.VERSION1}}"; fi
  INSPECT_IMAGE:
    sh: podman images -q {{.NAME}}
  INSPECT_VOLUME:
    sh: podman volume ls | grep {{.VOLUME}} | cut -f8 -d' '
  INSPECT_NETWORK:
    sh: podman network ls | grep {{.NETWORK}} | cut -f8 -d' '

tasks:
  default:
    desc: Shows task descriptions
    cmds:
      - task --list

  build:
    desc: Builds image
    sources:
      - Containerfile
    cmds:
      - podman build -t {{.NAME}}:{{.VERSION}} .
    status:
      - podman inspect --type image {{.NAME}}:{{.VERSION}}
  
  network:
    desc: Creates network
    cmds:
      - podman network create {{.NETWORK}}
    status:
      - podman inspect --type network {{.NETWORK}}
  
  volume:
    desc: Creates volume
    cmds:
      - podman volume create {{.VOLUME}}
    status:
      - podman inspect --type volume {{.VOLUME}}
  
  service:
    desc: Runs service
    deps:
      - build
      - network
      - volume
    cmds:
      - podman run -it --rm --name {{.CONTAINER}} --network {{.NETWORK}} --volume {{.VOLUME}}:/mnt/{{.VOLUME}} {{.NAME}}:{{.VERSION}} /bin/bash
  
  clean:
    desc: Removes image
    cmds:
      - podman rmi {{.NAME}}
    status:
      - if [ "{{.INSPECT_IMAGE}}" == "" ]; then exit 0; else exit 1; fi
  
  clean-volume:
    desc: Removes volume
    cmds:
      - podman volume rm {{.VOLUME}}
    status:
      - if [ "{{.INSPECT_VOLUME}}" == "" ]; then exit 0; else exit 1; fi

  clean-network:
    desc: Removes network
    cmds:
      - podman network rm {{.VOLUME}}
    status:
      - if [ "{{.INSPECT_NETWORK}}" == "" ]; then exit 0; else exit 1; fi
  
  clobber:
    desc: Removes image, volume, and network
    deps:
      - clean
      - clean-volume
      - clean-network
